spring:
  application:
    name: cobre
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/taller
    username: taller
    password: taller
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
cloud:
  aws:
    region: us-east-1
    access-key: taller
    secret-key: taller
    endpoint: http://localhost:4566
    log-registry-table: DeliveryLogs
    event-queue: notification-event-queue
    retry-queue: notification-retry-queue
    dlq-queue: notification-dead-letter-queue
